name: Greetings

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        id: create_comment
        with:
          comment-author: 'fairdataihub-bot'
          issue-number: ${{ github.event.number }}
          body: |
            🎉🎉 Thanks for opening this PR/Issue 🤗 Please wait while the maintainer(s) review it
